// INTEGRATION_GAP[LOBBY-COMMUNITY-WRITES] (build-required): see docs/DEVELOPMENT_GAPS.md#lobby-community-writes.
import {readFileSync,writeFileSync,mkdirSync,renameSync} from 'node:fs';
import path from 'node:path';
import {randomUUID} from 'node:crypto';
import {runtimeDir} from './paths.mjs';
export const learningStandard={version:1,levels:['beginner','intermediate','advanced','all-levels'],formats:['guide','video','course','reference','tool','collection'],topics:['understand','use-templates','combine-mechanics','build-frontend','test-deploy','troubleshoot']};
const fail=(message,status=400)=>{throw Object.assign(new Error(message),{status});};
const text=(v,max)=>typeof v==='string'&&v.trim()&&v.length<=max?v.trim():fail('Required text is missing or too long');
export function canonicalLearningUrl(value){let url;try{url=new URL(text(value,2000));}catch{fail('Use a valid public HTTPS resource link');}if(url.protocol!=='https:'||url.username||url.password)fail('Use a public HTTPS link without credentials');url.hash='';for(const key of [...url.searchParams.keys()])if(key.startsWith('utm_')||['fbclid','gclid'].includes(key))url.searchParams.delete(key);return url.href.replace(/\/$/,'');}
export function createCommunityLearning(root=runtimeDir){const file=path.join(root,'community-learning.json');const read=()=>{try{return JSON.parse(readFileSync(file,'utf8'));}catch(e){if(e.code==='ENOENT')return [];throw e;}};
 return {list:read,add(input,creator,existing=[]){if(!input||typeof input!=='object'||Array.isArray(input))fail('Expected a resource object');const url=canonicalLearningUrl(input.url),rows=read();if([...rows,...existing].some(r=>{try{return canonicalLearningUrl(r.sourceUrl||r.docsUrl||r.demoUrl)===url;}catch{return false;}}))fail('This resource is already in the library. Search for its title or link.',409);
 for(const field of ['level','format','topic'])if(!learningStandard[field==='level'?'levels':field==='format'?'formats':'topics'].includes(input[field]))fail(`Choose a valid ${field}`);
 const now=new Date().toISOString();const record={id:'community:learn:'+randomUUID(),type:'learn',native:false,ecosystem:text(input.ecosystem,60).toLowerCase(),title:text(input.title,120),summary:text(input.summary,700),category:input.topic,topic:input.topic,level:input.level,format:input.format,sourceUrl:url,docsUrl:url,repoUrl:null,demoUrl:null,network:null,readiness:'conceptual',license:null,prerequisites:[text(input.prerequisites,500)],setupHint:text(input.whyUseful,700),tags:['community-shared',input.topic],creator:{name:text(input.originalAuthor,160),url:null},sharedBy:{name:creator.name,url:'/creators/'+creator.id},attribution:'Original author: '+text(input.originalAuthor,160),verification:'unverified',tariCompatible:null,signals:{},provenance:{sourceId:'community-learning',sourceName:'Community recommendation',upstreamUrl:url,sourceUpdatedAt:null,fetchedAt:null,freshness:'unverified'},submittedAt:now,submittedBy:creator.id,schemaVersion:1};rows.push(record);mkdirSync(root,{recursive:true});writeFileSync(file+'.tmp',JSON.stringify(rows,null,2));renameSync(file+'.tmp',file);return record;}};
}
