import {safeHref} from '../../../shared/safeLinks.mjs';
import {useEffect,useState} from 'react';
import {Link,useSearchParams} from 'react-router-dom';
import {api,type Resource} from '../api';
import {MediaThumb} from '../media';
import {seedWorkflow} from '../../../shared/workflow.mjs';
import {newCommerceDraft,type CommerceDraft} from '../../../shared/assetCommerce.mjs';
import AssetCommerceEditor from './AssetCommerceEditor';
import './Assets.css';
type Asset=Resource & {assetKind:string;access?:string;filename?:string;bytes?:number;commerce?:CommerceDraft;commerceRevision?:number};
const categories=[['','Everything'],['pack','Packs & libraries'],['asset','Individual assets'],['workflow','Creation tools']];
export default function Assets(){
 const [params]=useSearchParams(),project=params.get('project');
 const [items,setItems]=useState<Asset[]>([]),[category,setCategory]=useState(''),[q,setQ]=useState(''),[provider,setProvider]=useState(''),[access,setAccess]=useState('');
 const [providers,setProviders]=useState<{id:string;name:string}[]>([]),[total,setTotal]=useState(0),[offset,setOffset]=useState(0),[refresh,setRefresh]=useState(0);
 const [error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[loading,setLoading]=useState(true),[showUpload,setShowUpload]=useState(false);
 const [title,setTitle]=useState(''),[description,setDescription]=useState(''),[creator,setCreator]=useState(''),[license,setLicense]=useState(''),[kind,setKind]=useState('asset'),[file,setFile]=useState<File|null>(null);
 const [commerce,setCommerce]=useState<CommerceDraft>(newCommerceDraft()),[editing,setEditing]=useState<Asset|null>(null);
 useEffect(()=>{let active=true;setLoading(true);setError('');const query=new URLSearchParams({q,kind:category,provider,access,offset:String(offset),limit:'48'});
 fetch('/api/assets?'+query).then(async r=>{if(!r.ok)throw Error('Could not load assets');return r.json();}).then(d=>{if(active){setItems(d.items);setProviders(d.providers);setTotal(d.total);}}).catch(e=>{if(active)setError(e.message);}).finally(()=>{if(active)setLoading(false);});return()=>{active=false;};},[q,category,provider,access,offset,refresh]);
 function filter(fn:()=>void){fn();setOffset(0);}
 async function upload(e:React.FormEvent){e.preventDefault();if(!file&&!editing)return;setError('');setNotice('');setBusy(true);try{
 let response;
 if(editing){response=await fetch(`/api/assets/${editing.id}/commerce`,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({commerce,expectedRevision:editing.commerceRevision||1})});}
 else {if(file!.size>10*1024*1024)throw Error('Choose a file no larger than 10 MB.');
 const base64=await new Promise<string>((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(String(r.result).split(',')[1]);r.onerror=()=>reject(Error('Could not read file'));r.readAsDataURL(file!);});
 response=await fetch('/api/assets',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({title,description,creator,license,kind,filename:file!.name,base64,commerce})});}
 const data=await response.json();if(!response.ok)throw Error(data.error||'Save failed');
 setEditing(data);setCategory('');setProvider('community-uploads');setAccess('');setOffset(0);setQ('');setRefresh(x=>x+1);setNotice('Saved to this hub. Listing and NFT settings are drafts; no network transaction was sent.');
 }catch(e:any){setError(e.message);}finally{setBusy(false);}}
 async function attach(asset:Asset){if(!project)return;setBusy(true);setError('');try{
  const detail=await api.project(project);const state=detail.state;if(!state)throw Error('Project state unavailable');
  const components=state.components||[];
  const graph=state.workflow||seedWorkflow(state);
  await api.publishProject(project,{state:{...state,components:components.some(c=>c.id===asset.id)?components:[...components,{id:asset.id,title:asset.title,ecosystem:'creative',type:asset.assetKind==='workflow'?'learn':'asset'}],workflow:graph.nodes.some(n=>n.resourceId===asset.id)?graph:{...graph,nodes:[...graph.nodes,{id:`asset-${Date.now()}`,role:asset.assetKind==='workflow'?'tool':'output',title:asset.title.slice(0,120),purpose:(asset.summary||'Describe asset usage').slice(0,2000),resourceId:asset.id,x:40,y:Math.min(2800,40+graph.nodes.length*150)}]}},expectedHead:detail.head||undefined,message:`Attach asset: ${asset.title}`,author:detail.project.author});
  setNotice(`Added ${asset.title} to the project and workflow. Reload any open project editor before continuing.`);
 }catch(e:any){setError(e.message);}finally{setBusy(false);}}

 function edit(a:Asset){setEditing(a);setCommerce(a.commerce||newCommerceDraft());setShowUpload(true);document.getElementById('asset-upload')?.scrollIntoView({behavior:'smooth'});}
 return <section className="assets-page"><Link to={project?`/project/${project}`:'/create'}>← {project?'Back to project':'Create'}</Link>
 <header className="assets-hero"><div><p className="eyebrow">THE CREATOR ASSET STORE</p><h1>Good assets.<br/>Wild combinations.</h1><p>Find textures, models, sprites, sound and tools. Add them to your project, or turn your own work into a community asset.</p></div><a href="#asset-upload" className="assets-contribute" onClick={()=>{setShowUpload(true);setEditing(null);setCommerce(newCommerceDraft());setFile(null);setTitle('');setDescription('');}}><span>＋</span><strong>Bring something new.</strong><p>Upload an asset. Design its listing. Give it an in-game identity.</p><b>Upload & customize →</b></a></header>
 <div className="asset-tabs">{categories.map(([id,name])=><button className={`btn ${category===id?'primary':''}`} aria-pressed={category===id} key={id} onClick={()=>filter(()=>setCategory(id))}>{name}</button>)}</div>
 <div className="asset-filters"><label className="lbl">Find an asset<input type="search" className="field" value={q} onChange={e=>filter(()=>setQ(e.target.value))} placeholder="Forest, pixel, footsteps, stone…"/></label><label className="lbl">Source<select className="field" value={provider} onChange={e=>filter(()=>setProvider(e.target.value))}><option value="">All sources</option>{providers.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label><label className="lbl">Availability<select className="field" value={access} onChange={e=>filter(()=>setAccess(e.target.value))}><option value="">All resources</option><option value="free">Free downloads</option><option value="sale-draft">Creator sale drafts</option></select></label></div>
 {error&&<p role="alert">{error} <button className="btn" onClick={()=>setRefresh(x=>x+1)}>Retry library</button></p>}{notice&&<p role="status">{notice}</p>}
 <div className="asset-section-heading"><h2>{provider==='community-uploads'?'Community creations':'Find your missing piece'}</h2><span className="muted">{total.toLocaleString()} resources</span></div>
 {loading?<p role="status">Loading assets…</p>:<><div className="asset-grid">{items.map(a=><article className="asset-card" key={a.id}><MediaThumb r={a}/><div className="asset-card-body"><div className="asset-card-meta"><span>{a.provenance?.sourceName||'Community'}</span><span>{a.access==='free'?'Free':a.access==='sale-draft'?'Sale draft':a.assetKind==='workflow'?'Tool / workflow':'Library'}</span></div><h3>{a.title}</h3><p>{a.summary}</p>{a.commerce?.sale.mode==='fixed-price'&&<strong>{a.commerce.sale.price} {a.commerce.sale.currencyLabel} · proposed price</strong>}{a.commerce?.nft.enabled&&<span className="badge">NFT design · {a.commerce.nft.preset}</span>}<div className="asset-actions">{a.sourceUrl&&<a className="btn" href={safeHref(a.sourceUrl)} target="_blank" rel="noreferrer">{a.filename?'Download file':'Browse / download ↗'}</a>}{project?<button className="btn" disabled={busy} onClick={()=>attach(a)}>Add to project</button>:<Link className="btn" to="/projects">Use in project</Link>}{a.filename&&<><button className="btn" onClick={()=>edit(a)}>Edit listing & NFT</button><a className="btn" href={safeHref(`/api/assets/${a.id}/commerce`)}>Export Ootle plan</a></>}</div></div></article>)}</div>
 {!items.length&&<p className="notice">No matches. Try another source or search.</p>}
 <div className="asset-pagination"><button className="btn" disabled={offset===0} onClick={()=>setOffset(n=>Math.max(0,n-48))}>← Previous</button><span>{total?offset+1:0}–{Math.min(offset+48,total)} of {total.toLocaleString()}</span><button className="btn" disabled={offset+48>=total} onClick={()=>setOffset(n=>n+48)}>Next →</button></div></>}
 <section id="asset-upload" className="asset-upload"><div className="asset-section-heading"><div><p className="eyebrow">FROM CREATOR TO COMMUNITY</p><h2>{editing?`Customize ${editing.title}`:'Share your own asset'}</h2></div><button className="btn" onClick={()=>setShowUpload(v=>!v)}>{showUpload?'Collapse':'Start an upload'}</button></div>
 {showUpload&&<form onSubmit={upload}>{!editing&&<><p className="muted">Upload a file for this hub’s shared library. Licensing review is deferred; attribution stays with the file.</p><div className="asset-form-grid"><label className="lbl">Title<input required maxLength={120} className="field" value={title} onChange={e=>setTitle(e.target.value)}/></label><label className="lbl">Category<select className="field" value={kind} onChange={e=>setKind(e.target.value)}>{categories.slice(1).map(([id,name])=><option key={id} value={id}>{name}</option>)}</select></label></div><label className="lbl">What is it for?<textarea required maxLength={2000} className="field" value={description} onChange={e=>setDescription(e.target.value)}/></label><div className="asset-form-grid"><label className="lbl">Creator<input required maxLength={120} className="field" value={creator} onChange={e=>setCreator(e.target.value)}/></label><label className="lbl">Reuse notes (optional, review later)<input maxLength={1000} className="field" value={license} onChange={e=>setLicense(e.target.value)}/></label></div><label className="lbl">File (up to 10 MB)<input required className="field" type="file" accept=".png,.jpg,.jpeg,.webp,.gif,.wav,.mp3,.ogg,.glb,.zip,.json" onChange={e=>setFile(e.target.files?.[0]||null)}/></label><p className="faint">Images, audio, GLB models, ZIP packs or JSON workflows. Files are stored as downloads, never executed.</p></>}
 <AssetCommerceEditor value={commerce} onChange={setCommerce}/>{error&&<p role="alert">{error}</p>}<div className="asset-actions"><button className="btn primary" disabled={busy||(!editing&&!file)}>{busy?'Saving…':editing?'Save listing & NFT draft':'Upload & save draft'}</button>{editing&&<><a className="btn" href={safeHref(`/api/assets/${editing.id}/commerce`)}>Export Ootle plan</a><button type="button" className="btn" onClick={()=>{setEditing(null);setCommerce(newCommerceDraft());setFile(null);setTitle('');setDescription('');}}>Upload another asset</button></>}</div></form>}
 </section></section>;
}
