import {safeHref} from '../../../shared/safeLinks.mjs';
import {NFT_PRESETS,MARKET_TEMPLATE,NFT_TEMPLATE,newCommerceDraft,type CommerceDraft} from '../../../shared/assetCommerce.mjs';
export default function AssetCommerceEditor({value,onChange}:{value:CommerceDraft;onChange:(v:CommerceDraft)=>void}){
 const sale=(patch:Partial<CommerceDraft['sale']>)=>onChange({...value,sale:{...value.sale,...patch}});
 const nft=(patch:Partial<CommerceDraft['nft']>)=>onChange({...value,nft:{...value.nft,...patch}});
 return <div className="asset-commerce">
 <div className="asset-editor-heading"><div><p className="eyebrow">MAKE IT YOUR OWN</p><h3>Distribution & game identity</h3></div><span className="badge">Draft · network not connected</span></div>
 <div className="asset-form-grid"><label className="lbl">Offer this asset as<select className="field" value={value.sale.mode} onChange={e=>sale({mode:e.target.value})}><option value="free">Free community download</option><option value="fixed-price">Fixed-price marketplace listing</option></select></label><label className="lbl">Available copies<input className="field" type="number" min="1" max="1000000" value={value.sale.inventory} onChange={e=>sale({inventory:Number(e.target.value)})}/></label>
 {value.sale.mode==='fixed-price'&&<><label className="lbl">Asking price<input className="field" inputMode="decimal" placeholder="10" value={value.sale.price} onChange={e=>sale({price:e.target.value})}/></label><label className="lbl">Payment currency label<input className="field" maxLength={16} value={value.sale.currencyLabel} onChange={e=>sale({currencyLabel:e.target.value})}/></label></>}</div>
 <p className="muted">Marketplace foundation: <a href={safeHref(MARKET_TEMPLATE.repository)} target="_blank" rel="noreferrer">Tari Market ↗</a>. Configure the offer now; checkout and paid delivery connect in a later network pass.</p>
 <label className="asset-toggle"><input type="checkbox" checked={value.nft.enabled} onChange={e=>nft({enabled:e.target.checked})}/> Prepare an NFT version of this asset</label>
 {value.nft.enabled&&<><div className="asset-form-grid"><label className="lbl">In-game use case<select className="field" value={value.nft.preset} onChange={e=>{const next=newCommerceDraft(e.target.value).nft;nft({...next,enabled:true,collectionName:value.nft.collectionName,symbol:value.nft.symbol,supplyCap:value.nft.supplyCap});}}>{NFT_PRESETS.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label><label className="lbl">Collection name<input className="field" maxLength={120} value={value.nft.collectionName} onChange={e=>nft({collectionName:e.target.value})}/></label><label className="lbl">Symbol<input className="field" maxLength={12} value={value.nft.symbol} onChange={e=>nft({symbol:e.target.value.toUpperCase()})}/></label><label className="lbl">Maximum NFT supply<input className="field" type="number" min="1" max="1000000" value={value.nft.supplyCap} onChange={e=>nft({supplyCap:Number(e.target.value)})}/></label>
 <label className="lbl">Who can mint?<select className="field" value={value.nft.mintAuthority} onChange={e=>nft({mintAuthority:e.target.value})}><option value="creator">Creator</option><option value="game-component">Game component</option></select></label><label className="lbl">Who can change game attributes?<select className="field" value={value.nft.updateAuthority} onChange={e=>nft({updateAuthority:e.target.value})}><option value="none">Nobody, immutable</option><option value="creator">Creator</option><option value="game-component">Game component</option></select></label></div>
 <div className="asset-inline"><label className="asset-toggle"><input type="checkbox" checked={value.nft.transferable} onChange={e=>nft({transferable:e.target.checked})}/> Transferable</label><label className="asset-toggle"><input type="checkbox" checked={value.nft.burnable} onChange={e=>nft({burnable:e.target.checked})}/> Consumable / burnable</label></div>
 <h4>Game attributes</h4><p className="muted">Customize stats, traits and progression. Mark only the fields that the chosen authority may update.</p>
 {value.nft.attributes.map((a,i)=><div className="asset-attribute" key={i}><label className="lbl">Name<input className="field" aria-label={`Attribute ${i+1} name`} value={a.name} onChange={e=>nft({attributes:value.nft.attributes.map((x,j)=>j===i?{...x,name:e.target.value}:x)})}/></label><label className="lbl">Value<input className="field" aria-label={`Attribute ${i+1} value`} value={a.value} onChange={e=>nft({attributes:value.nft.attributes.map((x,j)=>j===i?{...x,value:e.target.value}:x)})}/></label><label className="asset-toggle"><input type="checkbox" checked={a.mutable} onChange={e=>nft({attributes:value.nft.attributes.map((x,j)=>j===i?{...x,mutable:e.target.checked}:x)})}/> Mutable</label><button className="btn" type="button" aria-label={`Remove attribute ${i+1}`} onClick={()=>nft({attributes:value.nft.attributes.filter((_,j)=>j!==i)})}>Remove</button></div>)}
 <button type="button" className="btn" disabled={value.nft.attributes.length>=32} onClick={()=>nft({attributes:[...value.nft.attributes,{name:`trait${value.nft.attributes.length+1}`,value:'',mutable:false}]})}>+ Add attribute</button>
 <p className="muted mt16">Based on the <a href={safeHref(`${NFT_TEMPLATE.repository}/blob/${NFT_TEMPLATE.revision}/${NFT_TEMPLATE.path}`)} target="_blank" rel="noreferrer">native Ootle NFT example ↗</a>. Your saved configuration can be exported for template implementation. No NFT is minted by saving.</p></>}
 </div>;
}
