import {useEffect,useState} from 'react';
import {Link} from 'react-router-dom';
type Standard={levels:string[];formats:string[];topics:string[]};
export default function ShareLearning({onShared}:{onShared:()=>void}){
 const [open,setOpen]=useState(false),[standard,setStandard]=useState<Standard|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[done,setDone]=useState('');
 const identity=()=>{try{return JSON.parse(localStorage.getItem('creator-profile')||'null');}catch{return null;}};
 useEffect(()=>{if(!open)return;fetch('/api/learn/submission-standard').then(async r=>{if(!r.ok)throw Error('Could not load the submission format. Close and try again.');setStandard(await r.json());}).catch(e=>setError(e.message));},[open]);
 async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const account=identity();if(!account){setError('Set up a creator profile before sharing.');return;}setBusy(true);setError('');try{const body={...Object.fromEntries(new FormData(e.currentTarget)),creatorId:account.id};const r=await fetch('/api/learn/resources',{method:'POST',headers:{'Content-Type':'application/json',Authorization:'Bearer '+account.key},body:JSON.stringify(body)});const d=await r.json();if(!r.ok)throw Error(d.error||'Could not share this resource');setDone(d.id);setOpen(false);onShared();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 return <section className="learn-share"><div><p className="learn-eyebrow">CURATED BY THE COMMUNITY</p><h2>Found a good strat? Share it.</h2><p>Add a favorite tutorial, tool or reference. Tell other creators what it helps them make.</p></div><button className="btn primary" onClick={()=>{setOpen(!open);setError('');}}> {open?'Close form':'Share a resource ↗'}</button>{done&&<p role="status">Added to the library. <Link to={'/resource/'+encodeURIComponent(done)}>View your resource →</Link></p>}
 {open&&<div className="learn-share-form">{!identity()?<p><Link to="/skills">Set up your creator profile in Skills</Link>, then return here to share resources under your name.</p>:<form onSubmit={submit}><p>Recommendations appear immediately as community-shared, unverified resources. Credit the original creator and link to their work.</p>{[['title','Resource title',120],['url','Original resource URL (HTTPS)',2000],['originalAuthor','Original author or organization',160],['ecosystem','Ecosystem or tool, e.g. tari-ootle, godot, playcanvas',60]].map(([name,label,max])=><label key={name}><span>{label}</span><input name={String(name)} required maxLength={Number(max)} type={name==='url'?'url':'text'}/></label>)}{[['summary','What will someone learn?',700],['whyUseful','Why do you recommend it? What can someone make with it?',700],['prerequisites','What should someone know or install first? Write “None” if nothing is needed.',500]].map(([name,label,max])=><label key={name}><span>{label}</span><textarea name={String(name)} required maxLength={Number(max)}/></label>)}<div className="learn-selects">{(['topic','level','format'] as const).map(k=><label key={k}>{k==='topic'?'Learning goal':k}<select name={k} required defaultValue=""><option value="" disabled>Choose {k}</option>{(standard?.[k==='topic'?'topics':k==='level'?'levels':'formats']||[]).map(v=><option value={v} key={v}>{v.replace(/-/g,' ')}</option>)}</select></label>)}</div><button className="btn primary" disabled={busy||!standard}>{busy?'Sharing…':'Share with the community'}</button></form>}{error&&<p role="alert">{error}</p>}</div>}</section>;
}
