import {safeHref} from '../../../shared/safeLinks.mjs';
import LearningProgress from '../components/LearningProgress';
import { safeSkillLink } from '../skillLinks';
import { useEffect, useState } from 'react';
import { Link, useParams } from 'react-router-dom';
type Skill={id:string;title:string;description:string;version:string;lifecycle:string;networks:string[];technicalValidatedAt:string|null;sourceCheckedAt:string;validation:{scope:string};sources:{url:string}[];issue:string;remaining:string[]};
export default function Skills(){
  const {slug}=useParams();const [items,setItems]=useState<Skill[]>([]);const [guide,setGuide]=useState<{metadata:Skill;markdown:string}|null>(null);const [error,setError]=useState('');const [loading,setLoading]=useState(true);const [q,setQ]=useState('');const [state,setState]=useState('all');const [copied,setCopied]=useState(false);
  useEffect(()=>{const controller=new AbortController();setError('');setLoading(true);setGuide(null);setCopied(false);
    fetch(slug?`/api/skills/${encodeURIComponent(slug)}`:'/api/skills',{signal:controller.signal}).then(async r=>{if(!r.ok)throw new Error('Could not load skills');return r.json();}).then(d=>{if(slug)setGuide(d);else setItems(d.skills);setLoading(false);}).catch(e=>{if(e.name!=='AbortError'){setError(e.message);setLoading(false);}});return()=>controller.abort();},[slug]);
  const shown=items.filter(m=>(state==='all'||m.lifecycle===state)&&`${m.title} ${m.description} ${m.networks.join(' ')}`.toLowerCase().includes(q.toLowerCase()));
  return <section style={{padding:'28px 0'}}><Link to="/learn">← Learn</Link> · <Link to="/skills">TariSkills</Link><h1>{guide?guide.metadata.title:'Current Tari knowledge for people and agents building together'}</h1>
    {loading&&<p>Loading skills…</p>}{error&&<p role="alert">{error}</p>}
    {!slug&&!loading&&<><p>Native Ootle guidance with pinned sources and explicit validation scope. Drafts are available for research; the <a href="/skills/SKILL.md">agent router</a> includes only verified entries.</p>
    <div className="row" style={{gap:12,margin:'20px 0',flexWrap:'wrap'}}><input aria-label="Search skills" placeholder="Search task or network" value={q} onChange={e=>setQ(e.target.value)}/><select aria-label="Validation lifecycle" value={state} onChange={e=>setState(e.target.value)}>{['all','verified','draft','stale','deprecated'].map(x=><option key={x}>{x}</option>)}</select></div>
    {!shown.length&&<p>No matching skills.</p>}<div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(min(100%,280px),1fr))',gap:16}}>{shown.map(m=><article className="panel" key={m.id}><p>{m.lifecycle} · v{m.version}</p><h2><Link to={`/skills/${m.id}`}>{m.title}</Link></h2><p>{m.description}</p><p className="muted">{m.validation.scope}</p><a href={safeHref(`/skills/${m.id}/SKILL.md`)}>Raw Markdown</a></article>)}</div></>}
    {guide&&<><LearningProgress key={slug} slug={slug!}/><p><strong>{guide.metadata.lifecycle}</strong> · v{guide.metadata.version} · {guide.metadata.networks.join(', ')}</p><p>{guide.metadata.validation.scope}</p><p>Source check: {guide.metadata.sourceCheckedAt}. Technical validation: {guide.metadata.technicalValidatedAt||'Not completed'}.</p><div className="row" style={{gap:12,flexWrap:'wrap'}}><a href={safeHref(`/skills/${slug}/SKILL.md`)}>Raw Markdown</a><a href={safeHref(guide.metadata.issue)}>Implementation ticket</a><a href={safeHref(`https://github.com/marguerite347/ootle-lobby/commits/main/creator-hub/skills/${slug}/SKILL.md`)}>History</a><button className="btn" onClick={async()=>{try{await navigator.clipboard.writeText(guide.markdown);setCopied(true);}catch{setError('Clipboard unavailable. Use the raw Markdown link to copy.');}}}>{copied?'Copied':'Copy skill'}</button></div><nav aria-label="Guide references"><h2>References and examples</h2><ul>{Array.from(guide.markdown.matchAll(/\[([^\]]+)\]\(([^)]+)\)/g)).map((m,i)=>{const url=safeSkillLink(m[2],`${window.location.origin}/skills/${slug}/`);return url?<li key={i}><a href={safeHref(url)}>{m[1]}</a></li>:null;})}</ul></nav><pre style={{whiteSpace:'pre-wrap',overflowWrap:'anywhere',lineHeight:1.7,fontFamily:'inherit'}}>{guide.markdown}</pre></>}
  </section>;
}
