import {safeHref} from '../../../shared/safeLinks.mjs';
import {skillBundleArchive} from '../skillBundle';
import ContestProjects from '../components/ContestProjects';
import {useEffect,useState} from 'react';
import {Link,useParams,useSearchParams} from 'react-router-dom';
import './SkillMarket.css';
import {SuccessNotice} from '../components/GameKit';
import LobbyTrail from '../components/LobbyTrail';
import CreatorLeaderboard from '../components/CreatorLeaderboard';
type Creator={id:string;name:string;bio:string;showWork:boolean;showActivity:boolean;projects:string[]};
type Item={id:string;creatorId:string;kind:string;title:string;description:string;version:string;price:number;downloads:number;weeklyDownloads:number;nativeSlug?:string;[key:string]:any};
const sections=['purpose','requirements','setup','instructions','verification','recovery'];
async function api(path:string,method='GET',body?:unknown,key?:string){const r=await fetch('/api/'+path,{method,headers:{'Content-Type':'application/json',...(key?{Authorization:'Bearer '+key}:{})},body:body?JSON.stringify(body):undefined});const d=await r.json();if(!r.ok)throw Error(d.error||'Request failed');return d;}
export default function SkillMarket(){
 const [searchParams,setSearchParams]=useSearchParams();
 const category=searchParams.get('category')||'';
 const lifecycle=searchParams.get('status')||'';
 const [limit,setLimit]=useState(24);
 function filter(key:string,value:string){const next=new URLSearchParams(searchParams);if(value)next.set(key,value);else next.delete(key);setSearchParams(next);}
 const q=searchParams.get('q')||'';
 const kind=searchParams.get('kind')||'all';
 const sort=searchParams.get('sort')==='weeklyDownloads'?'weeklyDownloads':'downloads';
 const {creatorId}=useParams();const [data,setData]=useState<{listings:Item[];creators:Creator[];categories?:{id:string;label:string;description:string}[]}>({listings:[],creators:[]});const [error,setError]=useState('');const [loading,setLoading]=useState(true);const [panel,setPanel]=useState('');const [selected,setSelected]=useState<Item|null>(null);const [busy,setBusy]=useState(false);const [notice,setNotice]=useState('');
 const [identity,setIdentity]=useState<{id:string;key:string}|null>(()=>{try{return JSON.parse(localStorage.getItem('creator-profile')||'null');}catch{return null;}});
 const refresh=()=>api('skill-market').then(setData).catch(e=>setError(e.message)).finally(()=>setLoading(false));useEffect(()=>{refresh();},[]);useEffect(()=>{setSelected(null);setLimit(24);setNotice('');},[creatorId,searchParams]);
 const me=data.creators.find(c=>c.id===identity?.id),profile=data.creators.find(c=>c.id===creatorId);
 const available=data.listings.filter(l=>(!creatorId||l.creatorId===creatorId)&&(!creatorId||profile?.showWork));
 const categories=(data.categories||[]).map(c=>({...c,count:available.filter(l=>l.categories?.includes(c.id)).length}));
 const shown=available.filter(l=>(!category||l.categories?.includes(category))&&(!lifecycle||l.lifecycle===lifecycle)&&(kind==='all'||l.kind===kind)&&q.toLowerCase().trim().split(/\s+/).every(word=>`${l.title} ${l.description}`.toLowerCase().includes(word))).sort((a,b)=>b[sort]-a[sort]||a.title.localeCompare(b.title));
 const activeCategory=categories.find(c=>c.id===category);
 const filtered=!!(q||category||lifecycle||kind!=='all');


 async function download(l:Item){setBusy(true);try{let visitor=localStorage.getItem('skill-visitor');if(!visitor){visitor=crypto.randomUUID();localStorage.setItem('skill-visitor',visitor);}const d=await api(`skill-market/${l.id}/download`,'POST',{visitor});const u=URL.createObjectURL(new Blob([skillBundleArchive(d.files) as BlobPart],{type:'application/zip'}));const a=document.createElement('a');a.href=u;a.download=`${l.id}.zip`;a.click();setTimeout(()=>URL.revokeObjectURL(u),1000);setNotice('Downloaded a bundled skill. Review its instructions and source before allowing your agent to use it.');await refresh();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setError('');const f=Object.fromEntries(new FormData(e.currentTarget));try{if(panel==='profile'){const input={...f,showWork:f.showWork==='on',showActivity:f.showActivity==='on',projects:String(f.projects||'').split('\n').map(x=>x.trim()).filter(Boolean)};if(identity)await api('creator-profiles/'+identity.id,'PUT',input,identity.key);else{const d=await api('creator-profiles','POST',input);const i={id:d.profile.id,key:d.editKey};localStorage.setItem('creator-profile',JSON.stringify(i));setIdentity(i);}}else{if(!identity)throw Error('Create a profile first');await api('skill-market','POST',{...f,creatorId:identity.id,price:Number(f.price)},identity.key);}setPanel('');setNotice('Saved successfully.');await refresh();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 return <section className="skill-market"><LobbyTrail section="Skills" /><header className="skill-hero"><div><p className="eyebrow">SKILLS</p><h1>{creatorId?profile?.name||'Creator profile':'Your agent needs a loadout.'}</h1><p>{creatorId?profile?.bio:'Open a bundle, then use Setup & download to equip your agent.'}</p></div><a className="btn primary" href="#skill-library">Browse bundles</a></header>
 {error&&!selected&&<p role="alert">{error}</p>}{notice&&!selected&&<SuccessNotice key={notice}>{notice}</SuccessNotice>}
 {panel&&<form className="skill-form panel" onSubmit={submit}><h2>{panel==='profile'?'Your creator profile':'Publish reusable agent instructions'}</h2><button type="button" className="btn" onClick={()=>setPanel('')}>Close</button>{panel==='profile'?<><label>Display name<input name="name" required maxLength={80} defaultValue={me?.name}/></label><label>About you<textarea name="bio" maxLength={1000} defaultValue={me?.bio}/></label><label className="check"><input type="checkbox" name="showWork" defaultChecked={me?.showWork??true}/> Show my work and project links</label><label className="check"><input type="checkbox" name="showActivity" defaultChecked={me?.showActivity??true}/> Show activity and include me in creator rankings</label><label>Projects you built, one URL per line<textarea name="projects" defaultValue={me?.projects.join('\n')}/></label><p>Visibility is on by default. Listings retain creator attribution. Editing is linked to this browser in the local prototype.</p></>:<><label>Type<select name="kind"><option value="skill">Agent skill</option><option value="workflow">Full workflow</option></select></label><label>Title<input name="title" required maxLength={120}/></label><label>Description<textarea name="description" required maxLength={500}/></label><label>Version<input name="version" required defaultValue="1.0.0" maxLength={30}/></label><label>Price in USD, 0 for free<input name="price" type="number" min="0" max="100000" step="0.01" defaultValue="0" required/></label>{sections.map(s=><label key={s}>{s}<textarea name={s} required maxLength={12000} placeholder={s==='instructions'?'Ordered steps, inputs, outputs and links to required components':`Describe ${s} so someone else can reproduce your results`}/></label>)}<p>Free bundles are downloadable. Paid listings remain previews until checkout and delivery are connected. Nothing executes automatically.</p></>}<button disabled={busy} className="btn primary">{busy?'Saving…':'Save and publish'}</button></form>}
 {creatorId?.startsWith('forum-')&&profile&&<ContestProjects creatorId={creatorId}/>}
 {creatorId&&profile?.showWork&&profile.projects.length>0&&<section className="panel"><h2>Also built by {profile.name}</h2>{profile.projects.map(p=><p key={p}><a href={safeHref(p)} target="_blank" rel="noreferrer">{p} ↗</a></p>)}</section>}
 <div className="skill-body"><div className="skill-results" id="skill-library"><div className="skill-filters"><input aria-label="Search skills" placeholder="Find a capability or workflow…" value={q} onChange={e=>filter('q',e.target.value)}/><select aria-label="Template type" value={kind} onChange={e=>filter('kind',e.target.value==='all'?'':e.target.value)}><option value="all">Skills + workflows</option><option value="skill">Skills</option><option value="workflow">Workflows</option></select><select aria-label="Sort templates" value={sort} onChange={e=>filter('sort',e.target.value)}><option value="downloads">Most downloaded</option><option value="weeklyDownloads">Trending this week</option></select><select aria-label="Guidance status" value={lifecycle} onChange={e=>filter('status',e.target.value)}><option value="">All guidance statuses</option>{[...new Set(available.map(l=>l.lifecycle))].sort().map(value=><option key={value} value={value}>{value}</option>)}</select></div>
 <div className="skill-results-heading"><div><h2>{activeCategory?.label||(category?'Unknown category':'All skills & workflows')}</h2><p role="status">{loading?'Loading skills…':`${shown.length} bundles`}</p></div>{filtered&&<button className="btn" onClick={()=>{const next=new URLSearchParams(searchParams);['q','category','kind','status'].forEach(k=>next.delete(k));setSearchParams(next);}}>Clear filters</button>}</div>
 {filtered&&<p className="skill-filter-summary">{[activeCategory?.label,q&&`Search: ${q}`,kind!=='all'&&kind,lifecycle].filter(Boolean).join(' · ')}</p>}
 {loading?<p>Loading library…</p>:creatorId&&!profile?<p>Creator not found.</p>:creatorId&&!profile?.showWork?<p>This creator has hidden their portfolio.</p>:<div className="skill-grid">{shown.slice(0,limit).map(l=><article className="skill-tile" key={l.id}><div className="skill-meta"><span>{l.kind==='skill'?'↗ AGENT SKILL':'⌘ WORKFLOW'}</span><span>{l.price?`$${l.price}`:'FREE'}</span></div><h2 id={`skill-title-${l.id}`}>{l.title}</h2><p>{l.description}</p><Link to={`/creators/${l.creatorId}`}>{data.creators.find(c=>c.id===l.creatorId)?.name||'Creator'}</Link><small>{l.lifecycle} · v{l.version}{(!creatorId||profile?.showActivity)&&<><br/>{l.downloads} downloads{l.weeklyDownloads>=3?` · Trending: ${l.weeklyDownloads} this week`:''}</>}</small><button className="btn" aria-expanded={selected?.id===l.id} aria-controls={selected?.id===l.id?`skill-detail-${l.id}`:undefined} onClick={()=>{setNotice('');setError('');setSelected(current=>current?.id===l.id?null:l);}}>{selected?.id===l.id?'Close details ×':'Setup & download →'}</button> {selected?.id===l.id&&<section className="skill-detail skill-detail-inline" id={`skill-detail-${l.id}`} aria-labelledby={`skill-title-${l.id}`}>
   {selected.sourceUrl&&<a href={safeHref(selected.sourceUrl)} target="_blank" rel="noreferrer">Source repository ↗</a>}
   <div className="skill-detail-layout">
     <div className="skill-detail-guidance">
       <p className="skill-detail-label">THE FIELD GUIDE</p>
       <h3>Know before you start.</h3>
       {selected.nativeSlug?<Link className="btn" to={`/skills/${selected.nativeSlug}`}>Read full guide & validation scope ↗</Link>:<>
         {selected.purpose && selected.purpose.trim()!==selected.description.trim()&&<p className="skill-detail-purpose">{selected.purpose}</p>}
         {(['requirements','setup','instructions','verification','recovery'] as const).map((key,index)=>selected[key]&&<details key={`${selected.id}-${key}`} open={key==='requirements'}>
           <summary><span className="skill-detail-number">0{index+1}</span><span>{{requirements:'What you’ll need',setup:'Set up your workspace',instructions:'Follow the workflow',verification:'Check the result',recovery:'If something goes wrong'}[key]}</span><span className="skill-detail-plus" aria-hidden="true">+</span></summary>
           <p>{selected[key]}</p>
         </details>)}
       </>}
     </div>
     <aside className="skill-detail-actions" aria-label="Use this skill">
       <p className="skill-detail-label">ADD IT TO YOUR LOADOUT</p><h3>Use it with your agent.</h3>
       <p>Take the full bundle into your project, then give your agent a clear starting point.</p>
       <button className="btn primary" disabled={busy||selected.price>0} onClick={()=>download(selected)}>{selected.price?'Paid download unavailable':busy?'Preparing bundle…':'Download bundle ↓'}</button>
       <button className="btn" onClick={async()=>{try{await navigator.clipboard.writeText(`Read the ${selected.kind==='skill'?'SKILL.md':'WORKFLOW.md'} I downloaded for ${selected.title}, version ${selected.version}. Review requirements and source links, preserve existing project instructions, then guide me through setup and verification. Ask before installing dependencies or making external changes. Do not claim success without checking the result.`);setNotice('Agent setup prompt copied.');}catch{setError('Clipboard unavailable. Follow the setup steps below.');}}}>Copy agent setup prompt</button>
       <ol><li><strong>Unpack</strong><span>Extract the ZIP and keep its supporting files together.</span></li><li><strong>Add to your project</strong><span>Save the folder in your agent’s supported skills directory.</span></li><li><strong>Put it to work</strong><span>Paste the setup prompt. Review the steps and verify the result.</span></li></ol>
       <small>{selected.price?'Checkout is not connected.':'Free bundle · Nothing runs automatically.'}</small>
       {notice&&<p className="skill-detail-feedback" role="status">{notice}</p>}{error&&<p role="alert">{error}</p>}
     </aside>
   </div>
 </section>}</article>)}{!shown.length&&<p className="skill-empty">{filtered?'No matches. Clear a filter to explore more skills.':'No skills published here yet.'}</p>}</div>}{shown.length>limit&&<div className="skill-more"><span>Showing {limit} of {shown.length}</span><button className="btn" onClick={()=>setLimit(n=>n+24)}>Show 24 more</button></div>}</div><aside className="skill-browse" aria-label="Browse skill categories"><h2>Browse categories</h2><button aria-pressed={!category} onClick={()=>filter('category','')}>All skills & workflows <span>{available.length}</span></button>{categories.map(c=><button key={c.id} aria-pressed={category===c.id} onClick={()=>filter('category',c.id)}>{c.label}<span>{c.count}</span></button>)}<p>Categories can overlap. Counts show this library before filters.</p><Link to="/learn">Explore learning guides →</Link></aside></div><details className="skill-notes"><summary>Setup notes and other ways in</summary><div className="skill-top"><Link to="/skills?board=budget#creator-arena">Build on a budget ↗</Link><Link to="/skills/learning-loop">Turn project lessons into skills ↗</Link><a href="/agent-start">Start here with any agent ↗</a><Link to="/learn">← Learn</Link><Link to="/skills/native">Native TariSkills reference ↗</Link></div><div className="skill-instruction"><p>FROM BUNDLE TO CAPABILITY</p><h2>Pick a skill. Check the setup. Put it to work.</h2><ol className="skill-use-steps"><li>Open a skill and check its requirements.</li><li>Download its bundle into your project.</li><li>Copy the setup prompt and verify the result.</li></ol><small>Works with agents that can read Markdown. Nothing runs automatically.</small><div className="skill-contribute"><button className="btn" onClick={()=>setNotice('Community publishing is read-only. Propose a reviewed bundle through GitHub.')}>Publish a skill or workflow ↗</button><button className="btn" onClick={()=>setNotice('Creator profile editing is not available on the public Lobby.')}>{identity?'Edit creator profile':'Set up your creator profile'}</button>{me&&<Link to={`/creators/${me.id}`}>View your profile →</Link>}</div></div></details><div className="skill-community"><CreatorLeaderboard creators={data.creators} listings={data.listings} loading={loading} failed={Boolean(error) && !data.creators.length} onJoin={()=>{setNotice('Community publishing is read-only. Propose a reviewed bundle through GitHub.');window.scrollTo({top:0,behavior:'smooth'});}}/></div>


 </section>;
}
