import ChallengeEntries from '../components/ChallengeEntries';
import MonthlyContest from '../components/MonthlyContest';
import {useEffect,useState} from 'react';
import {Link} from 'react-router-dom';
import './Challenges.css';
import {SuccessNotice} from '../components/GameKit';
import ChallengeCard, {type ChallengeEdition as Edition} from '../components/ChallengeStory';
import LobbyTrail from '../components/LobbyTrail';
function useChallenges(){const[items,setItems]=useState<Edition[]>([]),[error,setError]=useState('');useEffect(()=>{let live=true;async function load(){try{const r=await fetch('/api/challenges');if(!r.ok)throw Error('Challenges could not load. Please refresh to try again.');const d=await r.json();if(live){setItems(d.editions);setError('');}}catch(e){if(live)setError((e as Error).message);}}void load();const interval=setInterval(load,60000);return()=>{live=false;clearInterval(interval)};},[]);return{items,error};}
export default function Challenges(){const{items,error}=useChallenges();const [done,setDone]=useState(false),[message,setMessage]=useState(''),[busy,setBusy]=useState(false);const current=items.find(e=>e.phase==='open');
 async function submit(event:React.FormEvent<HTMLFormElement>){event.preventDefault();setBusy(true);setMessage('');try{const identity=JSON.parse(localStorage.getItem('creator-profile')||'null');if(!identity?.id||!identity?.key)throw Error('Create your profile in Skills first, then return to submit.');const body={...Object.fromEntries(new FormData(event.currentTarget)),creatorId:identity.id,editionId:current?.id};const response=await fetch('/api/challenges/submissions',{method:'POST',headers:{'Content-Type':'application/json',Authorization:'Bearer '+identity.key},body:JSON.stringify(body)});const result=await response.json();if(!response.ok)throw Error(result.error||'Submission failed');setDone(true);setMessage('Submission saved with your project version. It is awaiting review, not a verified reward claim.');}catch(e){setMessage((e as Error).message);}finally{setBusy(false);}}
 return <><LobbyTrail section="Challenges" /><section className="hero"><span className="release-label">CHALLENGES & CONTESTS</span><h1>Chat, can you build this?</h1><p className="lede">Weekly prompts, community contests and the projects made for them. Find a brief, check the deadline, build something and share your entry.</p></section><nav className="challenge-section-nav" aria-label="Challenge sections"><a href="#weekly">Weekly challenges ↓</a><a href="#monthly-contest">Monthly contest ↓</a><a href="#entries">Community entries ↓</a><a href="#calendar">Calendar & past editions ↓</a></nav>{error&&<p role="alert">{error}</p>}{current&&<><section id="weekly"><h2>This week’s Creator Jam</h2><ChallengeCard edition={current}/></section><section id="submit" className="section challenge-submit"><div><h2>Show your entry.</h2><p>Publish your work in Projects, then submit its ID and evidence of this week’s contribution. Your exact saved version is recorded. Your summary, project and evidence link will appear in the entries gallery. One submission per creator and project each week.</p><Link to="/projects">Your projects →</Link> · <Link to="/skills">Set up a creator profile →</Link></div><form onSubmit={submit}><label>Project ID<input name="projectId" required maxLength={81} placeholder="e.g. my-game-ed73bc"/></label><label>What changed this week?<textarea name="summary" required maxLength={1600}/></label><label>Demo, recording or evidence URL<input name="evidenceUrl" type="url" required placeholder="https://…" maxLength={2000}/></label><button className="btn primary" disabled={busy||done}>{done?'Submitted':busy?'Submitting…':'Submit your contribution'}</button>{message&&(done?<SuccessNotice>{message}</SuccessNotice>:<p role="status">{message}</p>)}</form></section></>}
 <MonthlyContest/>
 <ChallengeEntries refresh={done}/>
 <section id="rewards" className="section challenge-rewards"><span className="release-label">COMMUNITY REWARD PATH</span><h2>Useful work unlocks shared opportunity.</h2><ol><li><strong>Contribute.</strong> Ship a demo, meaningful Riff or documented improvement.</li><li><strong>Verify.</strong> Review the exact version, evidence, credits and independent use. Raw clicks, self-reported play counts and token volume do not qualify.</li><li><strong>Unlock.</strong> A funded edition can unlock its published community reward pool when its verified goal is reached.</li><li><strong>Pay and report.</strong> Apply the edition’s announced allocation rules and record approved payouts and receipts.</li></ol><p><strong>Local pilot: no reward pool is funded and payouts are not connected.</strong> Five accepted contributions is the proposed initial community target. Submission counts are real; verification and payout automation are still to be built. A submission alone never authorizes a payment.</p></section>
 <section id="calendar" className="section upcoming-challenges"><div className="upcoming-heading"><span className="release-label">PLAN YOUR NEXT BUILD</span><h2>Coming up</h2><p>A new prompt each Monday. Find an idea that sparks something.</p></div><div className="challenge-calendar">{items.filter(e=>e.phase==='upcoming').map(e=><article className="upcoming-edition" key={e.id}><div className="upcoming-date"><span>WEEK {e.number}</span><time dateTime={e.startDate}>{new Date(e.startDate+'T12:00:00Z').toLocaleDateString('en-US',{month:'short',day:'numeric',timeZone:'UTC'})}</time></div><div className="upcoming-content"><h3>{e.title}</h3><p className="upcoming-focus">{e.metric}</p><details><summary>Explore the brief <span aria-hidden="true">↗</span></summary><p>{e.brief}</p></details></div><span className="upcoming-status">Upcoming</span></article>)}</div></section>
 <section className="section"><h2>Previous editions</h2>{items.filter(e=>e.phase==='archive').map(e=><article className="card" key={e.id}><h3>{e.title}</h3><p>{e.startDate} · {e.submitted} submissions · verification pending</p></article>)}{!items.some(e=>e.phase==='archive')&&<p>The first edition is underway. Completed weeks will appear here automatically.</p>}</section>
 <p className="faint">Inspired by the <a href="https://orlandoo.itch.io/portfolio-builders-jams">Portfolio Builders weekly format</a>. Tari prompts are original and AI-friendly. Independent program, no affiliation.</p></>;
}
