// INTEGRATION_GAP[WB-SYNC] (local-only): see docs/DEVELOPMENT_GAPS.md#wb-sync.
import {useEffect,useRef,useState,type ChangeEvent} from 'react';
import {Link} from 'react-router-dom';
import {zipSync,strToU8} from 'fflate';
import CodeEditor from '../workbench/CodeEditor';
import LearnResources from '../workbench/LearnResources';
import PublishPanel,{emptyDraft} from '../workbench/PublishPanel';
import {DISCONNECTED,getCapabilities,runWorkspace,deployArtifact,askAssistant,type Capabilities,type Run} from '../workbench/api';
import {filePathError,initialStore,newWorkspace,parseStore,STORAGE_KEY,validateFiles,type Workspace,type WorkspaceStore} from '../workbench/model';
import '../workbench/Workbench.css';

type Panel='files'|'search'|'compile'|'test'|'deploy'|'publish'|'resources';
const panels:{id:Panel;label:string;icon:string}[]=[{id:'files',label:'Files',icon:'files'},{id:'search',label:'Search',icon:'search'},{id:'compile',label:'Compile',icon:'compile'},{id:'test',label:'Test',icon:'test'},{id:'deploy',label:'Deploy',icon:'deploy'},{id:'publish',label:'Publish',icon:'publish'},{id:'resources',label:'Learn',icon:'learn'}];
function Icon({name}:{name:string}){const paths:Record<string,string>={files:'M8 3h10v13H8z M5 7H3v14h11v-2',search:'M16 16l5 5 M18 10a8 8 0 1 1-16 0 8 8 0 0 1 16 0',compile:'m9 3-5 10h7l-1 8 10-13h-8l2-5',test:'m5 12 4 4L20 5 M20 12v7H3V3h10',deploy:'M12 16V3 m-5 5 5-5 5 5 M4 15v6h16v-6',publish:'M3 12 21 3l-6 18-4-8-8-1 M11 13l10-10',learn:'M3 4h7l2 2 2-2h7v15h-7l-2 2-2-2H3z M12 6v15'};return <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.6" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true"><path d={paths[name]||paths.files}/></svg>;}
function restore(){try{const raw=localStorage.getItem(STORAGE_KEY);return {store:raw?parseStore(raw):initialStore(),error:''};}catch{return {store:initialStore(),error:'Your saved workspace could not be read. Export this workspace before leaving; the existing browser backup will not be overwritten.'};}}
export default function Workbench(){
 const initial=useRef<ReturnType<typeof restore>>();if(!initial.current)initial.current=restore();
 const [store,setStore]=useState<WorkspaceStore>(initial.current.store),[saveError,setSaveError]=useState(initial.current.error);
 const workspace=store.workspaces.find(w=>w.id===store.activeId)!;
 const [panel,setPanel]=useState<Panel>('files'),[home,setHome]=useState(true),[tabs,setTabs]=useState<string[]>([workspace.activeFile]);
 const [assistantOpen,setAssistantOpen]=useState(true),[filesVisible,setFilesVisible]=useState(false),[consoleOpen,setConsoleOpen]=useState(true);
 const [caps,setCaps]=useState<Capabilities>(DISCONNECTED),[notice,setNotice]=useState(''),[logs,setLogs]=useState<string[]>(['Ready. Open a file or start with the Tari Counter template.']);
 const [busy,setBusy]=useState(false),[run,setRun]=useState<{result:Run;source:string;workspaceId:string}|null>(null),[prompt,setPrompt]=useState(''),[messages,setMessages]=useState<{role:string;text:string}[]>([]),[asking,setAsking]=useState(false);
 const [query,setQuery]=useState(''),[dialogMode,setDialogMode]=useState<'workspace'|'file'|'rename'|null>(null),[name,setName]=useState(''),[dialogError,setDialogError]=useState('');
 const dialog=useRef<HTMLDialogElement>(null),nameInput=useRef<HTMLInputElement>(null),fileInput=useRef<HTMLInputElement>(null),folderInput=useRef<HTMLInputElement>(null),abort=useRef<AbortController|null>(null);
 const currentSource=JSON.stringify(workspace.files),sourceRef=useRef(currentSource);sourceRef.current=currentSource;
 const canDeploy=!!(caps.deploy&&run?.result.status==='succeeded'&&run.result.artifact&&run.source===currentSource&&run.workspaceId===workspace.id);
 useEffect(()=>{void getCapabilities().then(setCaps);const media=window.matchMedia('(min-width:1100px)');const compact=()=>{if(!media.matches)setAssistantOpen(false);};compact();media.addEventListener('change',compact);return()=>{abort.current?.abort();media.removeEventListener('change',compact);};},[]);
 useEffect(()=>{if(initial.current?.error)return;try{localStorage.setItem(STORAGE_KEY,JSON.stringify(store));setSaveError('');}catch{setSaveError('Browser storage is full or unavailable. Download your workspace before leaving.');}},[store]);
 useEffect(()=>{if(!saveError)return;const warn=(e:BeforeUnloadEvent)=>{e.preventDefault();e.returnValue='';};window.addEventListener('beforeunload',warn);return()=>window.removeEventListener('beforeunload',warn);},[saveError]);
 useEffect(()=>{if(dialogMode){dialog.current?.showModal();nameInput.current?.focus();}else dialog.current?.close();},[dialogMode]);
 function update(change:Partial<Workspace>){setStore(current=>({...current,workspaces:current.workspaces.map(w=>w.id===current.activeId?{...w,...change}:w)}));}
 function edit(value:string){update({files:{...workspace.files,[workspace.activeFile]:value}});}
 function openFile(path:string){update({activeFile:path});setTabs(current=>current.includes(path)?current:[...current,path]);setHome(false);if(panel==='publish')setPanel('files');setFilesVisible(false);}
 function selectPanel(next:Panel){setPanel(next);setFilesVisible(next!=='publish');if(next==='publish'){setHome(false);setConsoleOpen(false);}}
 function openDialog(mode:'workspace'|'file'|'rename'){setDialogMode(mode);setName(mode==='rename'?workspace.activeFile:'');setDialogError('');}
 function addWorkspace(next:Workspace){if(store.workspaces.length>=12){setNotice('You have 12 workspaces. Export your work before starting another.');return;}setStore(current=>({...current,activeId:next.id,workspaces:[...current.workspaces,next]}));setTabs([next.activeFile]);setHome(false);setPanel('files');setFilesVisible(false);setRun(null);setMessages([]);setNotice(`Opened ${next.name}.`);}
 function submitDialog(){
  const value=name.trim();if(!value){setDialogError('Enter a name.');return;}
  if(dialogMode==='workspace'){if(value.length>80){setDialogError('Use 80 characters or fewer.');return;}addWorkspace(newWorkspace(value));}
  else {
   const error=filePathError(value);if(error){setDialogError(error);return;}
   if(Object.prototype.hasOwnProperty.call(workspace.files,value)&&value!==workspace.activeFile){setDialogError('A file with that name already exists.');return;}
   if(dialogMode==='file'&&Object.prototype.hasOwnProperty.call(workspace.files,value)){setDialogError('A file with that name already exists.');return;}
   const files={...workspace.files};if(dialogMode==='rename'){files[value]=files[workspace.activeFile];delete files[workspace.activeFile];if(value===workspace.activeFile)files[value]=workspace.files[value];}else files[value]='';
   const invalid=validateFiles(files);if(invalid){setDialogError(invalid);return;}
   update({files,activeFile:value});setTabs(current=>[...new Set([...current.filter(path=>dialogMode!=='rename'||path!==workspace.activeFile),value])]);setHome(false);
  }
  setDialogMode(null);setFilesVisible(false);
 }
 async function importFiles(event:ChangeEvent<HTMLInputElement>){
  const chosen=Array.from(event.target.files||[]);event.target.value='';if(!chosen.length)return;
  try{
   const files:Record<string,string>={};let skipped=0;
   for(const file of chosen){const path=file.webkitRelativePath?file.webkitRelativePath.split('/').slice(1).join('/'):file.name;if(filePathError(path)){skipped++;continue;}if(file.size>300000)throw new Error(`${path} exceeds 300 KB.`);if(Object.keys(files).length>=100)throw new Error('Import up to 100 text files.');files[path]=await file.text();}
   const error=validateFiles(files);if(error)throw new Error(error);
   addWorkspace({id:crypto.randomUUID(),name:chosen[0].webkitRelativePath.split('/')[0]||'Imported workspace',files,activeFile:Object.keys(files).find(path=>path.endsWith('.rs'))||Object.keys(files)[0]});
   if(skipped)setNotice(`Imported workspace. Skipped ${skipped} dependency, credential or unsupported paths.`);
  }catch(error){setNotice(error instanceof Error?error.message:'Import failed.');}
 }
 function download(submission=false){
  const error=validateFiles(workspace.files);if(error){setNotice(error);return;}
  const files:Record<string,Uint8Array>=Object.fromEntries(Object.entries(workspace.files).map(([path,value])=>[path,strToU8(value)]));
  if(submission)files['ootle-submission.json']=strToU8(JSON.stringify({schemaVersion:1,status:'draft',workspaceName:workspace.name,...(workspace.publication||emptyDraft(workspace.name))},null,2));
  const zip=zipSync(files),url=URL.createObjectURL(new Blob([new Uint8Array(zip)],{type:'application/zip'}));const link=document.createElement('a');link.href=url;link.download=`${workspace.name.replace(/[^a-z0-9_-]/gi,'-')}${submission?'-submission':''}.zip`;link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);setNotice(submission?'Submission downloaded. It has not been published.':'Workspace downloaded.');
 }
 async function execute(action:'compile'|'test'){
  setConsoleOpen(true);setPanel(action);if(!caps[action]){setLogs([`${action==='compile'?'Compiler':'Test runner'} is not connected. Export the workspace to run it with your own tools.`]);return;}
  const invalid=validateFiles(workspace.files);if(invalid){setLogs([invalid]);return;}
  if(action==='compile')setRun(null);setBusy(true);setLogs([`${action==='compile'?'Compiling':'Testing'} ${workspace.name}…`]);const source=currentSource;abort.current=new AbortController();
  try{const result=await runWorkspace(workspace,action,abort.current.signal);setLogs([...result.logs,source===sourceRef.current?`${action} ${result.status}.`:'Workspace changed during this run. Run again before deployment.']);if(action==='compile')setRun({result,source,workspaceId:workspace.id});}catch(error){setLogs([error instanceof Error?error.message:'Run failed.']);}finally{setBusy(false);abort.current=null;}
 }
 async function deploy(){if(!canDeploy||!run?.result.artifact)return;setBusy(true);setConsoleOpen(true);try{const result=await deployArtifact(run.result.artifact.id);if(result.status!=='submitted'||!result.transactionId)throw new Error('Deployment was not confirmed.');setLogs([`Testnet transaction submitted: ${result.transactionId}`,result.templateAddress?`Template: ${result.templateAddress}`:'Waiting for network confirmation.']);}catch(error){setLogs([error instanceof Error?error.message:'Deployment failed.']);}finally{setBusy(false);}}
 async function send(){if(!prompt.trim()||asking||!caps.assistant)return;const text=prompt;setPrompt('');setAsking(true);setMessages(current=>[...current,{role:'You',text}]);try{const result=await askAssistant(workspace,text);if(typeof result.message!=='string')throw new Error('No assistant response received.');setMessages(current=>[...current,{role:'Tari Assistant',text:result.message}]);}catch(error){setMessages(current=>[...current,{role:'Connection',text:error instanceof Error?error.message:'Assistant unavailable.'}]);}finally{setAsking(false);}}
 const searchResults=query.trim()?Object.entries(workspace.files).flatMap(([path,value])=>value.split('\n').flatMap((line,index)=>line.toLowerCase().includes(query.toLowerCase())?[{path,line:index+1,text:line}]:[])).slice(0,50):[];
 const folderNames=[...new Set(Object.keys(workspace.files).filter(path=>path.includes('/')).map(path=>path.split('/')[0]))];
 function fileButton(path:string){return <button key={path} className={`wb-file${!home&&workspace.activeFile===path?' selected':''}`} onClick={()=>openFile(path)}><span aria-hidden="true">{path.endsWith('.rs')?'rs':path.endsWith('.toml')?'◇':'≡'}</span>{path.includes('/')?path.split('/').slice(1).join('/'):path}</button>;}
 return <div className="wb-app">
  <header className="wb-topbar"><Link to="/" className="wb-brand" aria-label="Back to Ootle Lobby"><img src="/ootle-jam-mark.svg" alt="" width="30" height="30"/><span><span>ootle <b>workbench</b></span><small>Back to Lobby</small></span></Link><label className="wb-workspace-select"><span className="sr-only">Workspace</span><select value={store.activeId} onChange={e=>{const next=store.workspaces.find(w=>w.id===e.target.value)!;setStore({...store,activeId:next.id});setTabs([next.activeFile]);setRun(null);setMessages([]);setHome(false);}}>{store.workspaces.map(w=><option key={w.id} value={w.id}>{w.name}</option>)}</select></label><span className="wb-local-badge">Local workspace</span><button className="wb-export" onClick={()=>download()}>Export</button><button className="wb-primary" onClick={()=>selectPanel('publish')}>Publish</button><button className="wb-assistant-toggle" aria-pressed={assistantOpen} onClick={()=>setAssistantOpen(!assistantOpen)}>AI</button></header>
  <div className={`wb-body${assistantOpen?' with-assistant':''}${filesVisible?' show-tools':''}`}>
   <nav className="wb-rail" aria-label="Workbench tools">{panels.map(item=><button key={item.id} className={panel===item.id?'active':''} aria-pressed={panel===item.id} onClick={()=>selectPanel(item.id)}><Icon name={item.icon}/><span>{item.label}</span></button>)}</nav>
   <aside className="wb-sidebar"><div className="wb-pane-heading"><span>{panels.find(item=>item.id===panel)?.label==='Files'?'FILE EXPLORER':panel.toUpperCase()}</span><button className="wb-mobile-close" onClick={()=>setFilesVisible(false)} aria-label="Close tools panel">×</button></div>
    {panel==='files'&&<><div className="wb-file-actions"><button onClick={()=>openDialog('file')}>+ New file</button><button onClick={()=>openDialog('workspace')} title="Create workspace">+</button></div><div className="wb-filetree"><div className="wb-tree-root">⌄ {workspace.name}</div>{folderNames.map(folder=><details key={folder} open><summary>{folder}</summary>{Object.keys(workspace.files).filter(path=>path.startsWith(`${folder}/`)).sort().map(fileButton)}</details>)}{Object.keys(workspace.files).filter(path=>!path.includes('/')).sort().map(fileButton)}</div><div className="wb-sidebar-bottom"><button onClick={()=>openDialog('rename')}>Rename file</button><button onClick={()=>fileInput.current?.click()}>Import files</button></div></>}
    {panel==='search'&&<div className="wb-panel-content"><label>Search workspace<input type="search" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Find in files…"/></label><p>{query?`${searchResults.length}${searchResults.length===50?'+':''} matches`:'Search the files in this workspace.'}</p>{searchResults.map((match,index)=><button className="wb-search-result" key={index} onClick={()=>openFile(match.path)}><strong>{match.path}:{match.line}</strong><small>{match.text}</small></button>)}</div>}
    {(panel==='compile'||panel==='test')&&<div className="wb-panel-content"><h2>{panel==='compile'?'Rust → WASM':'Template tests'}</h2><p>{panel==='compile'?'Compile your Tari template for the Ootle.':'Run the workspace’s Rust tests before deploying.'}</p><label>Target<input readOnly value={panel==='compile'?'wasm32-unknown-unknown':'Local engine'}/></label><button className="wb-primary" disabled={busy||!caps[panel]} onClick={()=>void execute(panel)}>{busy?'Running…':panel==='compile'?'Compile workspace':'Run tests'}</button><p className="wb-service-note">{caps[panel]?'Runner connected':panel==='compile'?'Compiler not connected':'Test runner not connected'}</p><code>{panel==='compile'?'cargo build --locked --release --target wasm32-unknown-unknown':'cargo test --locked'}</code><button onClick={()=>download()}>Download source</button></div>}
    {panel==='deploy'&&<div className="wb-panel-content"><h2>Deploy to Ootle</h2><label>Network<input value="Testnet" readOnly/></label><p>Compile the current workspace, then publish its WASM template to the testnet.</p><button className="wb-primary" disabled={!canDeploy||busy} onClick={()=>void deploy()}>Deploy template</button><p className="wb-service-note">{!caps.deploy?'Deployment not connected':!canDeploy?'Compile this revision first.':'Ready for testnet deployment.'}</p><a href="https://ootle.tari.com/guides/getting-started/" target="_blank" rel="noreferrer">Tari setup guide</a></div>}
    {panel==='publish'&&<div className="wb-panel-content"><h2>Give it a home.</h2><p>Contest entries go to October Submissions. Everything else goes to Community Projects.</p><Link to="/#october-submissions">October Submissions</Link><Link to="/#community-projects">Community Projects</Link><p className="wb-service-note">Network deployment and publishing a lobby listing are separate actions.</p><button className="wb-mobile-close" onClick={()=>setFilesVisible(false)}>Edit listing</button></div>}
    {panel==='resources'&&<LearnResources/>}
   </aside>
   <main className="wb-center">
    <div className="wb-editor-toolbar"><button className="wb-compile-button" disabled={busy} onClick={()=>void execute('compile')}><span aria-hidden="true">▶</span> Compile</button><span>{home?'Workspace':workspace.activeFile}</span><button onClick={()=>setConsoleOpen(!consoleOpen)} aria-expanded={consoleOpen}>Output</button></div>
    <div className="wb-tabs" aria-label="Open files"><button className={home&&panel!=='publish'?'selected':''} onClick={()=>{setHome(true);if(panel==='publish')setPanel('files');}}>Home</button>{tabs.filter(path=>Object.prototype.hasOwnProperty.call(workspace.files,path)).map(path=><div key={path} className={!home&&workspace.activeFile===path&&panel!=='publish'?'selected':''}><button onClick={()=>openFile(path)}>{path}</button><button className="wb-close-tab" aria-label={`Close ${path}`} onClick={()=>{setTabs(current=>current.filter(item=>item!==path));if(workspace.activeFile===path)setHome(true);}}>×</button></div>)}{panel==='publish'&&<button className="selected">Publish</button>}</div>
    <div className="wb-editor-area">
     {panel==='publish'?<PublishPanel key={workspace.id} workspace={workspace} connected={caps.publish} onChange={publication=>update({publication})} onExport={()=>download(true)}/>:home?<div className="wb-home"><div className="wb-home-wordmark"><img src="/ootle-jam-mark.svg" width="38" height="38" alt=""/><div><h1>Ootle Workbench</h1><p>Build. Test. Make it yours.</p></div></div><div className="wb-section-label">START</div><button className="wb-start-card featured" onClick={()=>openDialog('workspace')}><span>+</span><div><strong>Create a new workspace</strong><small>Start with a Tari Rust template</small></div></button><button className="wb-start-card" onClick={()=>openFile(workspace.activeFile)}><span>▶</span><div><strong>Start coding</strong><small>Open {workspace.activeFile}</small></div></button><button className="wb-start-card" onClick={()=>selectPanel('resources')}><Icon name="learn"/><div><strong>Learn Tari</strong><small>Templates, guides and agent skills</small></div></button><div className="wb-section-label">OPEN</div><div className="wb-home-open"><button onClick={()=>folderInput.current?.click()}><Icon name="files"/>Open folder</button><button onClick={()=>fileInput.current?.click()}>Import files</button></div><div className="wb-section-label">CREATE & SHARE</div><button className="wb-start-card" onClick={()=>selectPanel('publish')}><Icon name="publish"/><div><strong>Publish to the lobby</strong><small>October Submissions or Community Projects</small></div></button><p className="wb-home-note">Your files stay in this browser. Export a copy whenever you need it.</p></div>:<CodeEditor key={`${workspace.id}/${workspace.activeFile}`} path={workspace.activeFile} value={workspace.files[workspace.activeFile]||''} onChange={edit}/>}
    </div>
    {consoleOpen&&<section className="wb-output" aria-label="Build output"><div><strong>OUTPUT</strong><span>{busy?'Running':caps.compile?'Runner connected':'Local workspace'}</span><button onClick={()=>setLogs([])}>Clear</button><button aria-label="Close output" onClick={()=>setConsoleOpen(false)}>×</button></div><pre role="log">{logs.join('\n')}</pre></section>}
   </main>
   {assistantOpen&&<aside className="wb-assistant"><div className="wb-pane-heading"><span>TARI ASSISTANT</span><button aria-label="Close assistant" onClick={()=>setAssistantOpen(false)}>×</button></div><div className="wb-assistant-thread">{messages.length?messages.map((message,index)=><div className="wb-message" key={index}><strong>{message.role}</strong><p>{message.text}</p></div>):<div className="wb-assistant-empty"><span aria-hidden="true">✦</span><p>What do you want<br/>to build on Tari?</p></div>}</div><div className="wb-assistant-compose"><div className="wb-prompt-chips">{['Explain','Test','Improve'].map(action=><button key={action} onClick={()=>setPrompt(`${action} ${workspace.activeFile}`)}>{action}</button>)}</div><label><span className="sr-only">Message Tari Assistant</span><textarea rows={3} value={prompt} onChange={e=>setPrompt(e.target.value)} placeholder="Ask about your template…"/></label><div><small>{caps.assistant?'Workspace context included':'Assistant not connected'}</small><button className="wb-primary" disabled={!caps.assistant||asking||!prompt.trim()} onClick={()=>void send()}>{asking?'Thinking…':'Send'}</button></div></div></aside>}
  </div>
  <footer className="wb-statusbar"><span role="status">{saveError||notice||'Saved in this browser'}</span><span>Rust / WASM <b>·</b> Tari Ootle</span></footer>
  <input ref={fileInput} type="file" multiple hidden onChange={event=>void importFiles(event)}/><input ref={folderInput} type="file" multiple hidden {...{webkitdirectory:''}} onChange={event=>void importFiles(event)}/>
  <dialog className="wb-dialog" ref={dialog} onCancel={()=>setDialogMode(null)}><form onSubmit={event=>{event.preventDefault();submitDialog();}}><h2>{dialogMode==='workspace'?'Create workspace':dialogMode==='rename'?'Rename file':'New file'}</h2><label>{dialogMode==='workspace'?'Workspace name':'File path'}<input ref={nameInput} required value={name} onChange={e=>setName(e.target.value)} placeholder={dialogMode==='workspace'?'my-tari-project':'src/my_template.rs'}/></label>{dialogMode==='workspace'&&<p>Includes the Tari Counter template, pinned dependencies and tests.</p>}{dialogError&&<p role="alert">{dialogError}</p>}<div><button type="button" onClick={()=>setDialogMode(null)}>Cancel</button><button className="wb-primary" type="submit">{dialogMode==='rename'?'Rename':'Create'}</button></div></form></dialog>
 </div>;
}
