import {safeHref} from '../../../shared/safeLinks.mjs';
import {useEffect,useId,useRef,useState} from 'react';
import {activeRequirements,attachSetupPlan,durableSetupPlan,rememberSetupPlan,setupHandoff,type SetupPlan,type SetupStatus} from './toolkitSetup';
export default function BuildSetupWizard({plan,brief,idea='',skills=[],projectId='',expectedHead=null,onAttached}:{plan:SetupPlan;brief:string;idea?:string;skills?:{id:string;title:string}[];projectId?:string;expectedHead?:string|null;onAttached?:()=>void}){
 const [step,setStep]=useState(0),[providers,setProviders]=useState(plan.enabledProviders),[target,setTarget]=useState('Confirm with creator'),[statuses,setStatuses]=useState<Record<string,SetupStatus>>({}),[notice,setNotice]=useState('');
 const heading=useRef<HTMLHeadingElement>(null),id=useId();
 const active=activeRequirements(plan,providers),ready=active.filter(item=>statuses[item.id]==='ready').length;
 const handoff=setupHandoff(brief,plan,providers,statuses,target);
 useEffect(()=>{rememberSetupPlan(durableSetupPlan({idea,plan,target,providers,skills,statuses}));},[idea,plan,target,providers,skills,statuses]);
 function navigate(next:number){setStep(next);setNotice('');requestAnimationFrame(()=>heading.current?.focus({preventScroll:true}));}
 async function copy(){try{await navigator.clipboard.writeText(handoff);setNotice('Setup and build brief copied. Your agent has the unresolved questions.');}catch{setNotice('Copy is unavailable. Open the full handoff below and select its text.');}}
 async function attach(){
  const stored=durableSetupPlan({idea,plan,target,providers,skills,statuses});
  rememberSetupPlan(stored);
  if(!projectId){setNotice('Open a saved project to attach this setup. It is included when you create the Studio project. Statuses are user-reported, not verified.');return;}
  try{await attachSetupPlan(projectId,expectedHead,stored);setNotice('Setup plan saved on this project. Statuses are user-reported, not verified. Nothing was published as a playable.');onAttached?.();}
  catch(error){setNotice(error instanceof Error?error.message:'Could not attach the setup plan.');}
 }
 return <section className="build-setup" aria-labelledby={id}>
  <div className="setup-heading"><div><span className="setup-eyebrow">GET YOUR BUILD READY</span><h3 id={id} ref={heading} tabIndex={-1}>{['Choose your setup','Connect what you need','Hand it to your agent'][step]}</h3></div><span>{step+1} / 3</span></div>
  <nav className="setup-steps" aria-label="Project setup steps">{['Shape','Access & checks','Agent handoff'].map((label,index)=><button type="button" key={label} aria-current={index===step?'step':undefined} onClick={()=>navigate(index)}><b>{index+1}</b>{label}</button>)}</nav>
  {step===0&&<div className="setup-shape"><p><strong>{plan.engine}</strong> · Keep the foundation’s pinned version. These selections prepare a setup plan; they don’t install or connect services.</p><label>Where should the first build run?<select className="field" value={target} onChange={event=>setTarget(event.target.value)}>{['Confirm with creator','Browser','Desktop','Mobile','Engine/editor preview first'].map(value=><option key={value}>{value}</option>)}</select></label><fieldset><legend>Add services only if the project needs them</legend>{[['huggingface','Hugging Face','Generate with a selected model or use gated resources'],['envato','Envato','Use licensed stock, templates or browser generation'],['audio','Voice, music & SFX','Use an external provider or a local audio model']].map(([key,title,description])=><label className="setup-service" key={key}><input type="checkbox" checked={providers.includes(key)} onChange={event=>setProviders(current=>event.target.checked?[...current,key]:current.filter(value=>value!==key))}/><span><strong>{title}</strong><small>{description}</small></span></label>)}</fieldset><p className="faint">A token or paid account is not required for every project. Check the exact resources you choose.</p></div>}
  {step===1&&<><p>No secrets go here. Mark what you know; your agent must verify the actual setup and ask for anything missing.</p><div className="setup-checks">{active.map(item=><div className="setup-check" key={item.id}><div><strong>{item.title}</strong><p>{item.verify}</p><a href={safeHref(item.url)} target="_blank" rel="noreferrer">Open setup guidance ↗</a><details><summary>What your agent should ask</summary><p>{item.ask}</p></details></div><label>Status for {item.title}<select className="field" value={statuses[item.id]||'unverified'} onChange={event=>setStatuses(current=>({...current,[item.id]:event.target.value as SetupStatus}))}><option value="unverified">Not checked yet</option><option value="needs-help">I need help / access</option><option value="ready">I have checked this</option></select></label></div>)}</div></>}
  {step===2&&<><div className="setup-receipt"><strong>{ready} / {active.length} checkpoints reported ready</strong><p>{active.length-ready?'Your agent will receive the unresolved questions and verification steps. You can hand off now; missing access stays explicit.':'Your agent still needs to verify the setup and record a small working trial.'}</p></div><h4>Questions your agent will bring back</h4><ol className="setup-questions">{active.filter(item=>statuses[item.id]!=='ready').map(item=><li key={item.id}>{item.ask}</li>)}</ol>{ready===active.length&&<p>No unresolved items reported.</p>}<button type="button" className="btn primary" onClick={attach}>Attach setup to this project</button><button type="button" className="btn" onClick={copy}>Copy setup + build brief ↗</button><details className="setup-export"><summary>Review the full handoff</summary><pre>{handoff}</pre></details><p className="faint">Attach saves this checklist on the project. Marking a check ready does not install credentials or connect an account. Statuses stay user-reported, not verified.</p></>}
  <div className="setup-navigation">{step>0&&<button type="button" className="btn" onClick={()=>navigate(step-1)}>← Back</button>}{step<2&&<button type="button" className="btn primary" onClick={()=>navigate(step+1)}>{step===0?'Check access →':'Prepare agent handoff →'}</button>}</div><p role="status">{notice}</p>
 </section>;
}
