import {useEffect,useState} from 'react';
export default function SubscribeForm({waitlist=false}:{waitlist?:boolean}) {
 const [config,setConfig]=useState<{available:boolean;privacyUrl:string|null}|null>(null);
 const [email,setEmail]=useState(''),[consent,setConsent]=useState(false),[topics,setTopics]=useState(waitlist?['launch','events','journal']:['journal']);
 const [busy,setBusy]=useState(false),[message,setMessage]=useState(''),[done,setDone]=useState(false);
 useEffect(()=>{fetch('/api/subscriptions/config').then(r=>{if(!r.ok)throw Error();return r.json();}).then(setConfig).catch(()=>setConfig({available:false,privacyUrl:null}));},[]);
 const toggle=(topic:string)=>setTopics(current=>current.includes(topic)?current.filter(item=>item!==topic):[...current,topic]);
 return <form className="subscribe-form" onSubmit={async event=>{event.preventDefault();if(!config?.available||busy)return;setBusy(true);setMessage('');try{const response=await fetch('/api/subscriptions',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email,topics,consent,website:''})});const result=await response.json();if(!response.ok)throw Error(result.error||'Signup could not be completed.');setMessage(result.message);setDone(true);setEmail('');}catch(error){setMessage(error instanceof Error?error.message:'Please try again later.');}finally{setBusy(false);}}}>
  <h2>{waitlist?'Get the invite.':'Keep me in the loop.'}</h2><p>{waitlist?'Choose launch updates, event invitations and stories from the creators building what comes next.':'Get new guides, community stories and creative prompts in your inbox.'}</p>
  {!config?<p role="status">Checking signup availability…</p>:!config.available?<div className="signup-unavailable" role="status"><strong>Signups are opening soon.</strong><p>Email delivery is being connected. No email is collected yet. You can read the journal and explore the Hub now.</p></div>:!done?<><label>Email address<input type="email" autoComplete="email" required maxLength={254} value={email} onChange={event=>setEmail(event.target.value)}/></label><fieldset><legend>Send me</legend>{[['launch','Ootle mainnet launch updates'],['events','Event invitations'],['journal','Creator Journal and community news']].map(([key,label])=><label className="signup-option" key={key}><input type="checkbox" checked={topics.includes(key)} onChange={()=>toggle(key)}/>{label}</label>)}</fieldset><label className="signup-option"><input type="checkbox" required checked={consent} onChange={event=>setConsent(event.target.checked)}/><span>I agree to receive the updates I selected. I can unsubscribe at any time. <a href={config.privacyUrl!} target="_blank" rel="noreferrer">Privacy notice ↗</a></span></label><button className="btn primary" disabled={busy||!topics.length}>{busy?'Sending…':waitlist?'Join the waitlist ↗':'Subscribe ↗'}</button><small>Confirm the email we send to finish signing up.</small></>:null}
  <p role="status" aria-live="polite">{message}</p>
 </form>;
}
